default_language_version:
  # Force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        files: "backend"
        args: ["--settings-path", "setup.cfg"]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        files: "backend"
        args: ["--config", "pyproject.toml"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: "backend"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast # Simply check whether files parse as valid python.
        files: "backend"
      - id: check-yaml
      - id: check-added-large-files # Prevent giant files from being committed. Default 500kB.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: trailing-whitespace
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer # Ensure newline at eof
