repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at. Run pre-commit autoupdate after py3
    hooks:
      # - id: check-ast # Simply check whether files parse as valid python.
      #   files: "jenkins/api"
      - id: check-yaml
      - id: check-added-large-files # Prevent giant files from being committed. Default 500kB.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: trailing-whitespace # Enable later
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-symlinks # Checks for symlinks which do not point to anything.
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
