service: envoylint

plugins:
  - serverless-python-requirements
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8

  environment:
    PATH: $PATH:/opt/lintubuntu

package:
  exclude:
    - .git/**
    - .idea/**
    - bin/**
    - tmp/**

layers:
  Envoyv1162:
    path: bin/envoy-1.16.2/
    name: envoyv1160
    description: Envoy binary from envoyproxy/envoy-1.16.2
    retain: false
    compatibleRuntimes:
      - go1.x
      - python3.8
    package:
      include:
        - bin/envoy-1.16.2/**

  Envoyv1160:
    path: bin/envoy-1.16.0/
    name: envoyv1160
    description: Envoy binary from envoyproxy/envoy-1.16.0
    retain: false
    compatibleRuntimes:
      - go1.x
      - python3.8
    package:
      include:
        - bin/envoy-1.16.0/**

  Envoyv1152:
    path: bin/envoy-1.15.2/
    name: envoyv1152
    description: Envoy binary from envoyproxy/envoy:v1.15.2
    retain: false
    compatibleRuntimes:
      - go1.x
      - python3.8
    package:
      include:
        - bin/envoy-1.15.2/**

  Envoyv1145:
    path: bin/envoy-1.14.5/
    name: envoyv1145
    description: Envoy binary from envoyproxy/envoy:v1.14.5
    retain: false
    compatibleRuntimes:
      - go1.x
      - python3.8
    package:
      include:
        - bin/envoy-1.14.5/**

  Envoyv1134:
    path: bin/envoy-1.13.4/
    name: envoyv1134
    description: Envoy binary from envoyproxy/envoy:v1.13.4
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.13.4/**

  Envoyv1127:
    path: bin/envoy-1.12.7/
    name: envoyv1127
    description: Envoy binary from envoyproxy/envoy:v1.12.7
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.12.7/**

  ctclamz:
    path: bin/ctcl/lintamz/ # required, path to layer contents on disk
    name: config_load_check_tool_amzlinux # optional, Deployed Lambda layer name
    description: envoy config check tool built on amazon linux 2 # optional, Description to publish to AWS
    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - python3.8
    package:
      include:
        - bin/ctcl/lintamz/**

  libatomic:
    path: ./lib/ # required, path to layer contents on disk
    name: libatomic # optional, Deployed Lambda layer name
    description: libatomic built on amazon linux # optional, Description to publish to AWS
    retain: false # optional, false by default. If true, laRyer versions are not deleted as new ones are created
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - python3.8
    package:
      include:
        - ./lib/**

  Envoyv1170:
    path: bin/envoy-1.17.0/
    name: envoyv1170
    description: Envoy binary from envoyproxy/envoy-1.17.0
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.17.0/**

functions:
  envlint:
    handler: main.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: CtclamzLambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: clct
          method: post
          cors: true

  envoyv1162:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1162LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1162
          method: post
          cors: true

  envoyv1160:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1160LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1160
          method: post
          cors: true

  envoyv1152:
    runtime: python3.6
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1152LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1152
          method: post
          cors: true

  envoyv1145:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1145LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1145
          method: post
          cors: true

  envoyv1134:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1134LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1134
          method: post
          cors: true

  envoyv1127:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1127LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1127
          method: post
          cors: true

  envoyv1170:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1170LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1170
          method: post
          cors: true
