service: envoylint

plugins:
  - serverless-python-requirements
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.10
  lambdaHashingVersion: 20200924
  # lambdaHashingVersion: 20201221 # Enable later, new hashing algo

package:
  exclude:
    - .git/**
    - .idea/**
    - tmp/**
    - bin/**
    - node_modules/**

########################
# LAYERS
########################
layers:
  libatomic:
    path: ./lib/ # required, path to layer contents on disk
    name: libatomic # optional, Deployed Lambda layer name
    description: libatomic built on amazon linux # optional, Description to publish to AWS
    retain: false # optional, false by default. If true, laRyer versions are not deleted as new ones are created
    package:
      include:
        - ./lib/**

  Envoyv1127:
    path: bin/envoy-1.12.7/
    name: envoyv1127
    description: Envoy binary from envoyproxy/envoy:v1.12.7
    retain: false
    package:
      include:
        - bin/envoy-1.12.7/**

  Envoyv1134:
    path: bin/envoy-1.13.4/
    name: envoyv1134
    description: Envoy binary from envoyproxy/envoy:v1.13.4
    retain: false
    package:
      include:
        - bin/envoy-1.13.4/**

  Envoyv1145:
    path: bin/envoy-1.14.5/
    name: envoyv1145
    description: Envoy binary from envoyproxy/envoy:v1.14.5
    retain: false
    package:
      include:
        - bin/envoy-1.14.5/**

  Envoyv1152:
    path: bin/envoy-1.15.2/
    name: envoyv1152
    description: Envoy binary from envoyproxy/envoy:v1.15.2
    retain: false
    package:
      include:
        - bin/envoy-1.15.2/**

  Envoyv1162:
    path: bin/envoy-1.16.2/
    name: envoyv1160
    description: Envoy binary from envoyproxy/envoy-1.16.2
    retain: false
    package:
      include:
        - bin/envoy-1.16.2/**

  Envoyv1171:
    path: bin/envoy-1.17.1/
    name: envoyv1171
    description: Envoy binary from envoyproxy/envoy-1.17.1
    retain: false
    package:
      include:
        - bin/envoy-1.17.1/**

  Envoyv1182:
    path: bin/envoy-1.18.2/
    name: envoyv1182
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.18.2/**

  Envoyv1190:
    path: bin/envoy-1.19.0/
    name: envoyv1190
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.19.0/**

  Envoyv1200:
    path: bin/envoy-1.20.0/
    name: envoyv1200
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.20.0/**

  Envoyv1210:
    path: bin/envoy-1.21.0/
    name: envoyv1210
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.21.0/**

  Envoyv1220:
    path: bin/envoy-1.22.0/
    name: envoyv1220
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.22.0/**

  Envoyv1231:
    path: bin/envoy-1.23.1/
    name: envoyv1231
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.23.1/**

  Envoyv1272:
    path: bin/envoy-1.27.2/
    name: envoyv1272
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.27.2/**

  Envoyv1280:
    path: bin/envoy-1.28.0/
    name: envoyv1280
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    package:
      include:
        - bin/envoy-1.28.0/**

########################
# FUNCTIONS
########################
functions:
  envoyv1127:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1127LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1127
          method: post
          cors: true

  envoyv1134:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1134LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1134
          method: post
          cors: true

  envoyv1145:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1145LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1145
          method: post
          cors: true

  envoyv1152:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1152LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1152
          method: post
          cors: true

  envoyv1162:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1162LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1162
          method: post
          cors: true

  envoyv1171:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1171LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1171
          method: post
          cors: true

  envoyv1182:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1182LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1182
          method: post
          cors: true

  envoyv1190:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1190LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1190
          method: post
          cors: true

  envoyv1200:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1200LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1200
          method: post
          cors: true

  envoyv1210:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1210LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1210
          method: post
          cors: true

  envoyv1220:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1220LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1220
          method: post
          cors: true

  envoyv1231:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1231LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1231
          method: post
          cors: true

  envoyv1272:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1272LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1272
          method: post
          cors: true

  envoyv1280:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1280LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1280
          method: post
          cors: true
