service: envoylint

plugins:
  - serverless-python-requirements
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  # lambdaHashingVersion: 20201221

package:
  exclude:
    - .git/**
    - .idea/**
    - tmp/**
    - bin/**

########################
# LAYERS
########################
layers:
  libatomic:
    path: ./lib/ # required, path to layer contents on disk
    name: libatomic # optional, Deployed Lambda layer name
    description: libatomic built on amazon linux # optional, Description to publish to AWS
    retain: false # optional, false by default. If true, laRyer versions are not deleted as new ones are created
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - python3.8
    package:
      include:
        - ./lib/**

  Envoyv1127:
    path: bin/envoy-1.12.7/
    name: envoyv1127
    description: Envoy binary from envoyproxy/envoy:v1.12.7
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.12.7/**

  Envoyv1134:
    path: bin/envoy-1.13.4/
    name: envoyv1134
    description: Envoy binary from envoyproxy/envoy:v1.13.4
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.13.4/**

  Envoyv1145:
    path: bin/envoy-1.14.5/
    name: envoyv1145
    description: Envoy binary from envoyproxy/envoy:v1.14.5
    retain: false
    compatibleRuntimes:
      - go1.x
      - python3.8
    package:
      include:
        - bin/envoy-1.14.5/**

  Envoyv1152:
    path: bin/envoy-1.15.2/
    name: envoyv1152
    description: Envoy binary from envoyproxy/envoy:v1.15.2
    retain: false
    compatibleRuntimes:
      - go1.x
      - python3.8
    package:
      include:
        - bin/envoy-1.15.2/**

  Envoyv1162:
    path: bin/envoy-1.16.2/
    name: envoyv1160
    description: Envoy binary from envoyproxy/envoy-1.16.2
    retain: false
    compatibleRuntimes:
      - go1.x
      - python3.8
    package:
      include:
        - bin/envoy-1.16.2/**

  Envoyv1171:
    path: bin/envoy-1.17.1/
    name: envoyv1171
    description: Envoy binary from envoyproxy/envoy-1.17.1
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.17.1/**

  Envoyv1182:
    path: bin/envoy-1.18.2/
    name: envoyv1182
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.18.2/**

  Envoyv1190:
    path: bin/envoy-1.19.0/
    name: envoyv1190
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.19.0/**

  Envoyv1200:
    path: bin/envoy-1.20.0/
    name: envoyv1200
    description: Envoy binary from envoyproxy/envoy dockerhub
    retain: false
    compatibleRuntimes:
      - python3.8
    package:
      include:
        - bin/envoy-1.20.0/**

########################
# FUNCTIONS
########################
functions:
  envoyv1127:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1127LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1127
          method: post
          cors: true

  envoyv1134:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1134LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1134
          method: post
          cors: true

  envoyv1145:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1145LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1145
          method: post
          cors: true

  envoyv1152:
    runtime: python3.6
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1152LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1152
          method: post
          cors: true

  envoyv1171:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1171LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1171
          method: post
          cors: true

  envoyv1182:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1182LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1182
          method: post
          cors: true

  envoyv1190:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1190LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1190
          method: post
          cors: true

  envoyv1200:
    handler: envoycmd.lambda_handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: Envoyv1200LambdaLayer }
      - { Ref: LibatomicLambdaLayer }
    events:
      - http:
          path: envoyv1200
          method: post
          cors: true
