name: CI

####################################
# Start the job on all push and PR #
####################################
on:
  pull_request:
    branches: [master, main]
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches: [master, main]

jobs:
  precommits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
          pre-commit install

      - name: Run pre-commits
        run: |
          pre-commit run --all-files

  lintyaml:
    runs-on: ubuntu-latest # Set the agent to run on

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint code
        uses: docker://github/super-linter:v3.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: false
