#############################
# Workflow to run pytest and pre-commit hooks
#############################
name: Pre-Commits

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [master, main]
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches: [master, main]

jobs:
  precommits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
          pre-commit install

      - name: Run pre-commits
        run: |
          pre-commit run --all-files
